image: trion/ng-cli-karma

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - cd angular-tour-of-heroes
  - npm install

stages:
  - test
#  - build

tests:
  stage: test
  script: node_modules/.bin/ng test --progress false --watch=false

e2e_tests:
  stage: test
  script: node_modules/.bin/ng e2e --progress false --watch=false
